name: Registry PR from Issue

on:
  issues:
    types: [opened, edited, reopened]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  make_pr:
    if: contains(join(github.event.issue.labels.*.name, ','), 'registry-update')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write issue body to file
        run: |
          printf "%s" "${{ github.event.issue.body }}" > issue_body.md

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Update people.json from issue
        run: |
          node scripts/update_people.mjs issue_body.md

      # OPTIONAL light gating:
      # If you set an Actions secret named REGISTRY_INVITE_CODE,
      # then issues without the code will be closed.
      - name: Gate by invite code (optional)
        env:
          REQUIRED: ${{ secrets.REGISTRY_INVITE_CODE }}
        run: |
          if [ -z "$REQUIRED" ]; then
            echo "No invite code required."
            exit 0
          fi
          CODE="$(cat .invitecode.txt | tr -d '\r\n')"
          if [ "$CODE" != "$REQUIRED" ]; then
            echo "Invite code mismatch."
            exit 2
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update registry entry"
          title: "Registry update"
          body: |
            Automated PR created from a registry update issue.
            - Issue: #${{ github.event.issue.number }}
          branch: "registry/update-${{ github.event.issue.number }}"
          delete-branch: true
          add-paths: |
            people.json

      - name: Comment on the issue with PR link
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Find the PR created by create-pull-request
            const prs = await github.rest.pulls.list({
              owner, repo, state: "open", per_page: 50
            });

            const pr = prs.data.find(p => (p.head && p.head.ref || "").startsWith(`registry/update-${issue_number}`));
            if (!pr) return;

            await github.rest.issues.createComment({
              owner, repo, issue_number,
              body: `✅ Thanks! I opened a PR for this update: ${pr.html_url}\n\nOnce merged, it will appear on the site.`
            });

      - name: If invite code mismatch, close issue with note
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            await github.rest.issues.createComment({
              owner, repo, issue_number,
              body: `⚠️ This update could not be processed (missing/incorrect invite code or workflow error). If you're in the group, ask the maintainer for the current invite code.`
            });

            await github.rest.issues.update({
              owner, repo, issue_number, state: "closed"
            });
